first commit
matveylplusplus/inst123-proj pull request #5
Opened 2023-11-07 17:59 UTC by jaylenli1631

2023-11-08 00:41 UTC, sawyerbyrd approved these changes
looks good man

2023-11-14 14:40 UTC, matveylplusplus requested changes
Almost perfect!! Just a few small things that need tweaking; see comments

2023-11-14 14:40 UTC, matveylplusplus commented on main.sql
> +);
```suggestion
CREATE DATABASE musik;

CREATE TABLE genres (
    genre_name TEXT CONSTRAINT genres_key PRIMARY KEY,
    genre_desc TEXT
);
```
1) Can't forget to actually create the database, or else we'll get a merge conflict :( (important!!)
2) Capitalizing datatypes makes it more sexy (not super important)
3) Line 2 and line 4 can be consolidated into one just to be a lil more succinct (also not super important, but nice to have)

2023-11-14 16:47 UTC, matveylpp approved these changes
W

2023-11-14 17:33 UTC, k-zrsn approved these changes

2023-11-14 17:34 UTC, k-zrsn approved these changes

2023-11-14 17:34 UTC, k-zrsn approved these changes

2023-11-14 18:23 UTC, merged